version: "3.9"

services:
  api:
    container_name: "calendar-api"
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_CONNECTION_DEV=${DB_CONNECTION_DEV}
      - DB_CONNECTION_PROD=${DB_CONNECTION_PROD}
      - SECRET_JWT_SEED=${SECRET_JWT_SEED}
    ports:
      - "4000:4000"
