version: "3.9"

services:
  api:
    container_name: "calendar-api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_CONNECTION_DEV=${DB_CONNECTION_DEV}
      - DB_CONNECTION_PROD=${DB_CONNECTION_PROD}
      - SECRET_JWT_SEED=${SECRET_JWT_SEED}
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db

  db:
    container_name: "calendar-db"
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGODB_DATABASE: calendar-db
    ports:
      - 27017:27017
volumes:
  data:
