version: "3.9"

services:
  server:
    container_name: calendar-api
    build:
      context: .
      target: ${NODE_ENV}
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_CONNECTION_DEV: ${DB_CONNECTION_DEV}
      DB_CONNECTION_PROD: ${DB_CONNECTION_PROD}
      SECRET_JWT_SEED: ${SECRET_JWT_SEED}
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
  db:
    container_name: calendar-db
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: calendar-db
    volumes:
      - ./data:/data/db
